services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    image: madwick/go:docker-go-cowin
    environment:
      - COWIN_URL=https://cdn-api.co-vin.in/api
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=gocowin_db_1
    ports:
      - 8080:8080
    command: ["./wait-for-postgres.sh", "gocowin_db_1", "./main"]
volumes:
  db:
    driver: local

