services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    container_name: gocowin_db
  api:
    image: madwick/go-rest:release1
    environment:
      - API_URL=https://api.publicapis.org
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=gocowin_db
    ports:
      - 8080:8080
    depends_on:
      - "db"
    command: ["./wait-for-postgres.sh", "gocowin_db", "./main"]
    container_name: gocowin_api
volumes:
  db:
    driver: local
